[[dependency]]
org = "ballerina"
name = "test"
version = "0.0.0"

[[dependency]]
org = "jclark"
name = "nballerina.types"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "jclark"
name = "nballerina.front"
version = "0.1.0"
repository = "local"


